"""Composition layers: the base rows plus the patches a developer adds.

``cdh`` loads one row list, built from ordered layers::

    base            --config FILE, else the packaged harness/cordis.yml
    home patch      ~/.javis/cordis-harness/cordis.patch.yml
    project patch   ./cordis.patch.yml
    --patch FILE    each one, in the order given

A patch row addressed by an existing ``id`` updates that row; a row with a new
``id`` is appended. Relative plugin paths (``./x.py``) resolve against the file
that wrote them, so a project laid out as::

    my-project/
      cordis.patch.yml        # - id: my-tool
      plugins/my_tool.py      #   name: ./plugins/my_tool.py

works from any working directory.

The merge output is what the loader mounts; ``cdh --dump-config`` prints it.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Iterable

import yaml

#: Harness home: session logs and the user-level patch live here.
#: Harness home under the Javis home; sessions and the user patch live here.
DEFAULT_HOME = "~/.javis/cordis-harness"

#: Patch file name, looked up in the harness home and in the working directory.
PATCH_NAME = "cordis.patch.yml"

#: Header written into the generated composition, so nobody edits it by hand.
GENERATED_HEADER = "# Generated by cdh from composition layers; edits are overwritten.\n"


class CompositionError(Exception):
    """A composition layer could not be read or merged."""


def read_rows(path: str | Path) -> list[dict[str, Any]]:
    """Read one composition file: a list of rows, or an ``insert:`` payload."""
    file = Path(path).expanduser()
    try:
        data = yaml.safe_load(file.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise CompositionError(f"composition file not found: {file}") from error
    except yaml.YAMLError as error:
        raise CompositionError(f"cannot parse {file}: {error}") from error
    if data is None:
        return []
    if isinstance(data, dict) and "insert" in data:
        data = data["insert"]
    if not isinstance(data, list):
        raise CompositionError(f"{file} must be a list of rows (or an `insert:` payload)")
    for row in data:
        if not isinstance(row, dict):
            raise CompositionError(f"{file}: every row must be a mapping, got {type(row).__name__}")
    return [dict(row) for row in data]


def resolve_names(rows: Iterable[dict[str, Any]], base_dir: Path) -> list[dict[str, Any]]:
    """Absolutize relative plugin paths against the layer's own directory.

    Dotted module names (``harness.plugins.tools``) pass through untouched;
    only file-shaped specifiers (``./x.py``, ``../pkg/x.py``, ``x.py``) are
    resolved, including inside ``group`` rows.
    """
    resolved: list[dict[str, Any]] = []
    for row in rows:
        row = dict(row)
        name = row.get("name")
        if isinstance(name, str) and _is_file_specifier(name):
            row["name"] = str((base_dir / name).resolve())
        group = row.get("group")
        if isinstance(group, list):
            row["group"] = resolve_names(group, base_dir)
        resolved.append(row)
    return resolved


def _is_file_specifier(name: str) -> bool:
    return (
        name.startswith("./")
        or name.startswith("../")
        or name.startswith("/")
        or name.endswith(".py")
        or os.sep in name
    )


def apply_patch(
    rows: list[dict[str, Any]],
    patch_rows: list[dict[str, Any]],
    *,
    source: str,
) -> list[dict[str, Any]]:
    """Merge one patch layer into ``rows`` (addressed by ``id``).

    A row updates every field it names: ``config`` replaces the whole config
    (a patch is a replacement, not a deep merge), ``disabled`` toggles a row,
    ``name``/``inject``/``provide``/``isolate`` are taken as given. Rows whose
    id is not present are appended in patch order.
    """
    index = {row.get("id"): position for position, row in enumerate(rows) if row.get("id")}
    merged = [dict(row) for row in rows]
    for patch_row in patch_rows:
        entry_id = patch_row.get("id")
        if not entry_id:
            raise CompositionError(f"{source}: every patch row needs an `id` (got {patch_row!r})")
        if entry_id in index:
            target = merged[index[entry_id]]
            for key, value in patch_row.items():
                if key != "id":
                    target[key] = value
        else:
            index[entry_id] = len(merged)
            merged.append(dict(patch_row))
    return merged


def patch_paths(
    *,
    home: str | Path | None = None,
    project: str | Path | None = None,
    extra: Iterable[str | Path] = (),
) -> list[Path]:
    """The patch layers that exist, in application order."""
    candidates: list[Path] = []
    if home is not None:
        candidates.append(Path(home).expanduser() / PATCH_NAME)
    if project is not None:
        candidates.append(Path(project).expanduser() / PATCH_NAME)
    candidates.extend(Path(path).expanduser() for path in extra)
    return [path for path in candidates]


def compose(
    base_path: str | Path,
    patches: Iterable[str | Path] = (),
) -> tuple[list[dict[str, Any]], list[Path]]:
    """Build the effective rows: base first, then each patch in order.

    Returns the merged rows and the layers that actually contributed (the
    existing patch files, in order).
    """
    base = Path(base_path).expanduser().resolve()
    rows = resolve_names(read_rows(base), base.parent)
    applied: list[Path] = []
    for patch_path in patches:
        path = Path(patch_path).expanduser()
        if not path.is_file():
            continue
        path = path.resolve()
        rows = apply_patch(rows, resolve_names(read_rows(path), path.parent), source=str(path))
        applied.append(path)
    return rows, applied


def dump(
    rows: list[dict[str, Any]],
    *,
    base: str | Path | None = None,
    patches: Iterable[str | Path] = (),
) -> str:
    """Render merged rows as the YAML text handed to the loader."""
    header = ["# cdh composition"]
    if base is not None:
        header.append(f"# base:    {Path(base).expanduser().resolve()}")
    for patch in patches:
        header.append(f"# patch:   {Path(patch).expanduser().resolve()}")
    header.append("# generated; edits are overwritten")
    return "\n".join(header) + "\n" + yaml.safe_dump(rows, sort_keys=False, allow_unicode=True)


def write(
    rows: list[dict[str, Any]],
    path: str | Path,
    *,
    base: str | Path | None = None,
    patches: Iterable[str | Path] = (),
) -> Path:
    """Write the merged rows to ``path`` (the loader reads a file)."""
    target = Path(path).expanduser()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(dump(rows, base=base, patches=patches), encoding="utf-8")
    return target
