/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_result$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_result$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_result$schema$value ??= z.union([z.object({
  'kind': z.literal("ready").readonly(),
}), z.object({
  'kind': z.literal("change").readonly(),
  'change': z.union([z.object({
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
}), z.object({
  'absolutePath': z.string().readonly(),
  'absent': z.literal(true).readonly(),
})]).readonly(),
})]))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_1$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_1$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_result$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_result$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_result$schema$value ??= z.object({
  'path': z.string().readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'type': z.union([z.literal("file"), z.literal("directory"), z.literal("other")]).readonly(),
  'size': z.number().readonly().optional(),
})).readonly(),
  'truncated': z.boolean().readonly(),
}))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_1$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_1$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_2$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_2$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_2$schema$value ??= z.object({
  'offset': z.number().readonly().optional(),
  'limit': z.number().readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_result$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_result$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_result$schema$value ??= z.object({
  'offset': z.number().readonly(),
  'text': z.string().readonly(),
  'lines': z.number().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_1$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_1$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_result$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_result$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_result$schema$value ??= z.object({
  'offset': z.number().readonly(),
  'data': z.string().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_1$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_1$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_2$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_2$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_2$schema$value ??= z.object({
  'offset': z.number().readonly().optional(),
  'length': z.number().readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_result$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_result$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_result$schema$value ??= z.object({
  'offset': z.number().readonly(),
  'data': z.string().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_1$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_1$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_2$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_2$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_2$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_result$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_result$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_result$schema$value ??= z.object({
  'offset': z.number().readonly(),
  'data': z.string().readonly(),
  'eof': z.boolean().readonly(),
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
}))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_0$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_0$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_1$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_1$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_result$schema$value
const _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_result$schema = () => (_deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_result$schema$value ??= z.object({
  'absolutePath': z.string().readonly(),
  'version': z.string().readonly(),
  'bytes': z.number().readonly().optional(),
}))

export const TYPERT = {
  package: '@deepseek-ai/dsh-api-workspace-files',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/changes',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'changes',
      mode: 'stream',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileWatchFrame',
        create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_changes_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":364,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/list',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/list:path',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceDirectoryListing',
        create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_list_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":336,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/read',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'read',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/read:path',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_1$schema,
          },
        },
        {
          name: 'range',
          wire: 'range',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileRange',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_parameter_2$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileText',
        create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_read_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":232,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readAll',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'readAll',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readAll:path',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileBytes',
        create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readAll_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":278,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readBytes',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'readBytes',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readBytes:path',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_1$schema,
          },
        },
        {
          name: 'range',
          wire: 'range',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceByteRange',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_parameter_2$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileBytes',
        create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readBytes_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":257,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readRelated',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'readRelated',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readRelated:path',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_1$schema,
          },
        },
        {
          name: 'relativePath',
          wire: 'relativePath',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/readRelated:relativePath',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_parameter_2$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileBytes',
        create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_readRelated_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":299,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/stat',
      service: 'workspaceFiles',
      namespace: 'workspaceFiles',
      method: 'stat',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'workspaceFileScope',
          wire: 'workspaceFileScopeId',
          source: 'lookup',
          lookup: 'workspaceFileScope',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_0$schema,
          },
        },
        {
          name: 'path',
          wire: 'path',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-workspace-files#workspaceFiles/stat:path',
            create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-workspace-files/types#WorkspaceFileStat',
        create: _deepseek_ai_dsh_api_workspace_files_workspaceFiles_stat_result$schema,
      },
      sourceLocation: {"file":"packages/api/workspace-files/src/index.ts","line":323,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host Remote file reads and workspace directory observations over the composed filesystem.",
        "summary": "Host Remote file reads and workspace directory observations over the composed filesystem.",
        "tags": [],
        "jsDoc": "/** Host Remote file reads and workspace directory observations over the composed filesystem. */",
        "key": "workspaceFiles",
        "exportName": "WorkspaceFiles",
        "members": [
          {
            "kind": "method",
            "name": "read",
            "signature": "@Remote async read( workspaceFileScope: WorkspaceFileScope, path: string, range: WorkspaceFileRange, signal: AbortSignal, ): Promise<WorkspaceFileText>",
            "summary": "Read one page of lines from a UTF-8 file readable by the filesystem backend.",
            "jsDoc": "/**\n * Read one page of lines from a UTF-8 file readable by the filesystem backend.\n * @param workspaceFileScope - header-derived workspace root for the Session identity on the wire.\n * @param path - absolute path or path relative to the workspace root; files outside it are allowed.\n * @param range - the line window; omitted fields take the page defaults.\n * @param signal - caller cancellation.\n * @returns the page, the file's version at the stat before it, and whether it reaches the last line.\n */"
          },
          {
            "kind": "method",
            "name": "readBytes",
            "signature": "@Remote async readBytes( workspaceFileScope: WorkspaceFileScope, path: string, range: WorkspaceByteRange, signal: AbortSignal, ): Promise<WorkspaceFileBytes>",
            "summary": "Read one byte window of a regular file readable by the filesystem backend: raw bytes, no text decoding and no binary rejection.",
            "jsDoc": "/**\n * Read one byte window of a regular file readable by the filesystem backend: raw\n * bytes, no text decoding and no binary rejection.\n * @param workspaceFileScope - header-derived workspace root for the Session identity on the wire.\n * @param path - absolute path or path relative to the workspace root; files outside it are allowed.\n * @param range - the byte window; omitted fields take the window defaults.\n * @param signal - caller cancellation.\n * @returns the window in base64, the file's version and size at the stat before it, and whether it reaches the last byte.\n */"
          },
          {
            "kind": "method",
            "name": "readAll",
            "signature": "@Remote async readAll(workspaceFileScope: WorkspaceFileScope, path: string, signal: AbortSignal): Promise<WorkspaceFileBytes>",
            "summary": "Read a complete regular file as bytes, subject to the configured full-file cap.",
            "jsDoc": "/**\n * Read a complete regular file as bytes, subject to the configured full-file cap.\n * @param workspaceFileScope - header-derived workspace root for the Session identity on the wire.\n * @param path - absolute or workspace-relative file path.\n * @param signal - caller cancellation.\n * @returns one complete base64 window with offset zero and eof true; oversized files fail with too-large.\n */"
          },
          {
            "kind": "method",
            "name": "readRelated",
            "signature": "@Remote async readRelated( workspaceFileScope: WorkspaceFileScope, path: string, relativePath: string, signal: AbortSignal, ): Promise<WorkspaceFileBytes>",
            "summary": "Read a complete file relative to another file's directory, including outside the workspace.",
            "jsDoc": "/**\n * Read a complete file relative to another file's directory, including outside the workspace.\n * @param workspaceFileScope - header-derived workspace root for the Session identity on the wire.\n * @param path - base file, absolute or workspace-relative.\n * @param relativePath - relative filesystem path, not a URL or absolute path.\n * @param signal - caller cancellation.\n * @returns the complete related file using the ordinary file-size and access checks.\n */"
          },
          {
            "kind": "method",
            "name": "stat",
            "signature": "@Remote async stat(workspaceFileScope: WorkspaceFileScope, path: string, signal: AbortSignal): Promise<WorkspaceFileStat>",
            "summary": "Report one regular file's identity, version, and size without its content.",
            "jsDoc": "/**\n * Report one regular file's identity, version, and size without its content.\n * @param workspaceFileScope - header-derived workspace root for the Session identity on the wire.\n * @param path - absolute path or path relative to the workspace root; files outside it are allowed.\n * @param signal - caller cancellation.\n * @returns the file's absolute path, current version, and byte size.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote async list(workspaceFileScope: WorkspaceFileScope, path: string, signal: AbortSignal): Promise<WorkspaceDirectoryListing>",
            "summary": "List the direct children of one directory inside the Session's workspace.",
            "jsDoc": "/**\n * List the direct children of one directory inside the Session's workspace.\n * @param workspaceFileScope - header-derived workspace root for the Session identity on the wire.\n * @param path - workspace path, absolute or relative to the workspace root.\n * @param signal - caller cancellation.\n * @returns the directory's children in the backend's stable name order, bounded by the entry cap.\n */"
          },
          {
            "kind": "method",
            "name": "changes",
            "signature": "@Remote({ mode: 'stream' }) changes(workspaceFileScope: WorkspaceFileScope, signal: AbortSignal): AsyncIterable<WorkspaceFileWatchFrame>",
            "summary": "Stream every `fs/observed` observation of a file inside the Session's workspace.",
            "jsDoc": "/**\n * Stream every `fs/observed` observation of a file inside the Session's\n * workspace. Only instrumented filesystem operations report here; the OS is\n * not watched.\n * @param workspaceFileScope - header-derived workspace root for the Session identity on the wire.\n * @param signal - generation cancellation.\n * @returns `ready` once the Host observation queue is active and the workspace\n *   root is resolved, then queued and live observations in emission order.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "WorkspaceByteRange",
            "declaration": "export interface WorkspaceByteRange {\n    readonly offset?: number;\n    readonly length?: number;\n}"
          },
          {
            "name": "WorkspaceDirectoryEntry",
            "declaration": "export interface WorkspaceDirectoryEntry {\n    readonly name: string;\n    readonly type: 'file' | 'directory' | 'other';\n    readonly size?: number;\n}"
          },
          {
            "name": "WorkspaceDirectoryListing",
            "declaration": "export interface WorkspaceDirectoryListing {\n    readonly path: string;\n    readonly entries: readonly WorkspaceDirectoryEntry[];\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "WorkspaceFileBytes",
            "declaration": "export interface WorkspaceFileBytes extends WorkspaceFileStat {\n    readonly offset: number;\n    readonly data: string;\n    readonly eof: boolean;\n}"
          },
          {
            "name": "WorkspaceFileChange",
            "declaration": "export type WorkspaceFileChange = { readonly absolutePath: string; readonly version: string; } | { readonly absolutePath: string; readonly absent: true; };"
          },
          {
            "name": "WorkspaceFileRange",
            "declaration": "export interface WorkspaceFileRange {\n    readonly offset?: number;\n    readonly limit?: number;\n}"
          },
          {
            "name": "WorkspaceFileScope",
            "declaration": "export interface WorkspaceFileScope {\n    readonly sessionId: SessionId;\n    readonly workspaceRoot: string;\n}"
          },
          {
            "name": "WorkspaceFileStat",
            "declaration": "export interface WorkspaceFileStat {\n    readonly absolutePath: string;\n    readonly version: string;\n    readonly bytes?: number;\n}"
          },
          {
            "name": "WorkspaceFileText",
            "declaration": "export interface WorkspaceFileText extends WorkspaceFileStat {\n    readonly offset: number;\n    readonly text: string;\n    readonly lines: number;\n    readonly eof: boolean;\n}"
          },
          {
            "name": "WorkspaceFileWatchFrame",
            "declaration": "export type WorkspaceFileWatchFrame = { readonly kind: 'ready'; } | { readonly kind: 'change'; readonly change: WorkspaceFileChange; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
